### ISSUE TITLE
Create feature/aks-aad-ingration

### ISSUE THREAD

**Issue by ThorSchutze** [tw3lveparsecs/tk-421#19]
Prep AAD Integration

Dependency on https://github.com/tw3lveparsecs/tk-421/issues/29#issue-1016162677

**Comment by tw3lveparsecs** [comment]
might want to take a look at #6 as that looks like it is related

**Comment by ThorSchutze** [comment]
👍🏻

Sent from my iPhone

On 2 Oct 2021, at 8:27 pm, tw3lveparsecs ***@***.***> wrote:

﻿

might want to take a look at #6<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftw3lveparsecs%2Ftk-421%2Fissues%2F6&data=04%7C01%7C%7C054262752a23460bed6808d9858f45c4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687672674990380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FdhlKpa6WmctPv9gTlyuy9Wlwag%2FbvVTe56cIB3S5xU%3D&reserved=0> as that looks like it is related

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftw3lveparsecs%2Ftk-421%2Fissues%2F19%23issuecomment-932728756&data=04%7C01%7C%7C054262752a23460bed6808d9858f45c4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687672675000337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Xv0KfXWORYqUhC2xnfA7cEg3ebrfttZE5ymIoRXruzY%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHFM3CWNGTM3YFXJN5C7LITUE3NB7ANCNFSM5FGGZ2KQ&data=04%7C01%7C%7C054262752a23460bed6808d9858f45c4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687672675000337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IBm3mEeHwKLgFK6Bu30ecUtnw3F8nXp6iiqosf4wwts%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C054262752a23460bed6808d9858f45c4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687672675000337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zUyQ%2FZxRCMEos9fBBrNFy%2F7B2idvA%2BRkGlMJJHA%2BAnA%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C054262752a23460bed6808d9858f45c4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687672675010293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8VF1w%2BLrRO1vsyaz%2BDJXBb8w9X9VeeNt1FFyJTseNKM%3D&reserved=0>.

**Comment by ThorSchutze** [comment]
Ah yes thought that revolved more around documenting what is done for this project

Sent from my iPhone

On 2 Oct 2021, at 8:59 pm, Thor Schutze ***@***.***> wrote:

﻿ 👍🏻

Sent from my iPhone

On 2 Oct 2021, at 8:27 pm, tw3lveparsecs ***@***.***> wrote:

﻿

might want to take a look at #6<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftw3lveparsecs%2Ftk-421%2Fissues%2F6&data=04%7C01%7C%7C054262752a23460bed6808d9858f45c4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687672674990380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FdhlKpa6WmctPv9gTlyuy9Wlwag%2FbvVTe56cIB3S5xU%3D&reserved=0> as that looks like it is related

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftw3lveparsecs%2Ftk-421%2Fissues%2F19%23issuecomment-932728756&data=04%7C01%7C%7C054262752a23460bed6808d9858f45c4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687672675000337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Xv0KfXWORYqUhC2xnfA7cEg3ebrfttZE5ymIoRXruzY%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHFM3CWNGTM3YFXJN5C7LITUE3NB7ANCNFSM5FGGZ2KQ&data=04%7C01%7C%7C054262752a23460bed6808d9858f45c4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687672675000337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IBm3mEeHwKLgFK6Bu30ecUtnw3F8nXp6iiqosf4wwts%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C054262752a23460bed6808d9858f45c4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687672675000337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zUyQ%2FZxRCMEos9fBBrNFy%2F7B2idvA%2BRkGlMJJHA%2BAnA%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C054262752a23460bed6808d9858f45c4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687672675010293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8VF1w%2BLrRO1vsyaz%2BDJXBb8w9X9VeeNt1FFyJTseNKM%3D&reserved=0>.
